language: node_js
node_js:
  - 'node'
cache:
  yarn: true
  directories:
    - 'site/node_modules'
before_install:
  - cd site
  - npm install -g yarn
before_script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis-CI"
  - git config credential.helper "store --file=../.git/credentials"
  - echo "https://${GITHUB_TOKEN}:@github.com" > ../.git/credentials
  - ./before.sh
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: 'site/dist'
  on:
    branch: master
